service: serverless-fido

provider:
  name: aws
  runtime: nodejs6.10
  environment:
    SLACK_CLIENT_ID: ${SLACK_CLIENT_ID}
    SLACK_CLIENT_SECRET: ${SLACK_CLIENT_SECRET}

functions:
  authorization:
    handler: handler.authorization
    events:
      - http:
          path: slack/authorization
          method: get

  fido:
    handler: handler.fido
    events:
      - http:
          path: slack/fido
          method: post
